import { CityDistrict, DemoScenario } from "../types/climate";

export const CITY_DISTRICTS: CityDistrict[] = [
  {
    id: "palakollu",
    name: "Palakollu",
    region: "West Godavari Delta",
    state: "Andhra Pradesh",
    type: "Lowland Alluvial Delta",
    coordinates: { lat: 16.529, lng: 81.729 },
    elevationM: 2.5,
    imperviousSurfacePercent: 68,
    treeCanopyPercent: 18,
    stormDrainageCapacityMmH: 22,
    primaryRiskPropensity: "Flood Risk",
    vulnerabilityDescription:
      "Alluvial delta basin with minimal slope. Intersected by irrigation canals that experience severe backflow and waterlogging during heavy precipitation.",
    baselineEnv: {
      temperatureC: 29.0,
      rainfall24hMm: 6.0,
      rainfallIntensityMmH: 1.5,
      humidityPercent: 62,
      condition: "Partly Cloudy / Humid",
      isSimulated: true,
    },
    zones: [
      {
        id: "pk-1",
        name: "Main Irrigation Outfall Canal",
        type: "Hydraulic Drainage Node",
        vulnerabilityFactor: "Siltation & tidal backflow bottleneck",
        riskSeverity: "Critical",
        coordinates: { x: 32, y: 68 },
        details: "Primary channel discharging runoff into lower Godavari basin; water accumulates rapidly.",
        infrastructureAtRisk: "Agricultural perimeter dykes, rural access culverts",
      },
      {
        id: "pk-2",
        name: "Town Market & Bus Station Underpass",
        type: "Commercial Core Lowland",
        vulnerabilityFactor: "Depressed roadway prone to 0.5m waterlogging",
        riskSeverity: "High",
        coordinates: { x: 52, y: 46 },
        details: "Dense commercial market with limited underground stormwater capacity.",
        infrastructureAtRisk: "Town municipal market stalls, regional bus terminal",
      },
      {
        id: "pk-3",
        name: "Railway Feeder Residential Ward",
        type: "Low-lying Residential Colony",
        vulnerabilityFactor: "Ground-level inundation in older housing blocks",
        riskSeverity: "Medium",
        coordinates: { x: 70, y: 35 },
        details: "Houses built on alluvial soil with high groundwater table.",
        infrastructureAtRisk: "Residential basements, localized drinking water borewells",
      },
    ],
  },
  {
    id: "narsapuram",
    name: "Narsapuram",
    region: "Godavari Coastal Estuary",
    state: "Andhra Pradesh",
    type: "Coastal Estuary & Port Town",
    coordinates: { lat: 16.435, lng: 81.696 },
    elevationM: 1.8,
    imperviousSurfacePercent: 72,
    treeCanopyPercent: 12,
    stormDrainageCapacityMmH: 20,
    primaryRiskPropensity: "Flood Risk",
    vulnerabilityDescription:
      "Estuary mouth where river meets Bay of Bengal. Tidal surge combined with heavy monsoon runoff triggers rapid coastal inundation.",
    baselineEnv: {
      temperatureC: 30.0,
      rainfall24hMm: 8.0,
      rainfallIntensityMmH: 2.0,
      humidityPercent: 68,
      condition: "Humid / Coastal Breeze",
      isSimulated: true,
    },
    zones: [
      {
        id: "ns-1",
        name: "River Estuary Embankment",
        type: "Riparian Tidal Barrier",
        vulnerabilityFactor: "Overtopping risk during high tide and upstream discharge",
        riskSeverity: "Critical",
        coordinates: { x: 40, y: 75 },
        details: "Riverbank edge with small boat jetties and fishing settlements.",
        infrastructureAtRisk: "Fisheries harbor infrastructure, coastal flood walls",
      },
      {
        id: "ns-2",
        name: "Old Port Road Corridor",
        type: "Arterial Transit Link",
        vulnerabilityFactor: "Depressed coastal road susceptible to tidal pooling",
        riskSeverity: "High",
        coordinates: { x: 60, y: 50 },
        details: "Sole connecting artery for emergency evacuation towards inland bypass.",
        infrastructureAtRisk: "Emergency hospital transit route, local power substation",
      },
    ],
  },
  {
    id: "vijayawada",
    name: "Vijayawada",
    region: "Krishna River Basin",
    state: "Andhra Pradesh",
    type: "Dense Riparian Urban Commercial Hub",
    coordinates: { lat: 16.506, lng: 80.648 },
    elevationM: 19.0,
    imperviousSurfacePercent: 86,
    treeCanopyPercent: 8,
    stormDrainageCapacityMmH: 38,
    primaryRiskPropensity: "Heat Risk",
    vulnerabilityDescription:
      "River valley surrounded by rocky Indrakeeladri hillocks. Concrete density generates intense micro-urban heat island during summer, while hills funnel flash runoff.",
    baselineEnv: {
      temperatureC: 32.5,
      rainfall24hMm: 2.0,
      rainfallIntensityMmH: 0.5,
      humidityPercent: 54,
      condition: "Sunny / Warm",
      isSimulated: true,
    },
    zones: [
      {
        id: "vj-1",
        name: "Besant Road Commercial Canyon",
        type: "High-Density Pedestrian Zone",
        vulnerabilityFactor: "Concrete heat retention and zero shade canopy",
        riskSeverity: "High",
        coordinates: { x: 48, y: 42 },
        details: "High foot-traffic retail street with dense masonry storefronts.",
        infrastructureAtRisk: "Unsheltered shoppers, outdoor market vendors",
      },
      {
        id: "vj-2",
        name: "Budameru Rivulet Lowland",
        type: "Flash Runoff Sump",
        vulnerabilityFactor: "Catchment basin subject to sudden urban inundation",
        riskSeverity: "High",
        coordinates: { x: 65, y: 62 },
        details: "Narrow drain taking runoff from northern hill slopes.",
        infrastructureAtRisk: "Northern bypass road, railway underbridge",
      },
    ],
  },
  {
    id: "visakhapatnam",
    name: "Visakhapatnam",
    region: "Eastern Ghats Coastal Strip",
    state: "Andhra Pradesh",
    type: "Coastal Port & Industrial Metropolis",
    coordinates: { lat: 17.686, lng: 83.218 },
    elevationM: 14.0,
    imperviousSurfacePercent: 80,
    treeCanopyPercent: 15,
    stormDrainageCapacityMmH: 42,
    primaryRiskPropensity: "Flood Risk",
    vulnerabilityDescription:
      "Bounded by hills on one side and sea on the other. Steep hill slope runoff pours into narrow urban coastal drainage corridors during intense rain events.",
    baselineEnv: {
      temperatureC: 28.5,
      rainfall24hMm: 4.0,
      rainfallIntensityMmH: 1.0,
      humidityPercent: 65,
      condition: "Partly Cloudy / Coastal Wind",
      isSimulated: true,
    },
    zones: [
      {
        id: "vsp-1",
        name: "Beach Road & Fishing Harbour Lowland",
        type: "Coastal Strip Infrastructure",
        vulnerabilityFactor: "Storm surge spray and sea-front surface pooling",
        riskSeverity: "High",
        coordinates: { x: 38, y: 65 },
        details: "Low elevation shoreline prone to wave overtopping during depressions.",
        infrastructureAtRisk: "Port cargo handling yards, coastal promenade",
      },
      {
        id: "vsp-2",
        name: "Gajuwaka Industrial Corridor",
        type: "Manufacturing Hardscape",
        vulnerabilityFactor: "High impervious surface and industrial waste heat",
        riskSeverity: "Medium",
        coordinates: { x: 62, y: 38 },
        details: "Heavy industrial hub with vast asphalt parking and concrete sheds.",
        infrastructureAtRisk: "Factory access roads, power grid transmission lines",
      },
    ],
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    region: "Deccan Plateau",
    state: "Telangana",
    type: "Metropolitan Plateau & Concrete Core",
    coordinates: { lat: 17.385, lng: 78.486 },
    elevationM: 540.0,
    imperviousSurfacePercent: 92,
    treeCanopyPercent: 7,
    stormDrainageCapacityMmH: 45,
    primaryRiskPropensity: "Heat Risk",
    vulnerabilityDescription:
      "High elevation Deccan rock terrain with sprawling asphalt corridors. Extreme Urban Heat Island (UHI) with thermal reflection reaching up to 45°C+ during peak summer.",
    baselineEnv: {
      temperatureC: 33.0,
      rainfall24hMm: 0.0,
      rainfallIntensityMmH: 0.0,
      humidityPercent: 42,
      condition: "Clear / Intense Sun",
      isSimulated: true,
    },
    zones: [
      {
        id: "hyd-1",
        name: "HITEC City & Madhapur Tech Corridor",
        type: "High-Rise Glass & Concrete Canyon",
        vulnerabilityFactor: "Radiative heat reflection from glass facades and dark asphalt",
        riskSeverity: "Critical",
        coordinates: { x: 45, y: 40 },
        details: "Expansive glass and concrete IT buildings creating extreme daytime radiant heat.",
        infrastructureAtRisk: "Pedestrian metro stations, commuter transit bus hubs",
      },
      {
        id: "hyd-2",
        name: "Musirambagh Low-Level Causeways",
        type: "River Drainage Dip",
        vulnerabilityFactor: "Flash runoff pooling during sudden monsoon downpours",
        riskSeverity: "High",
        coordinates: { x: 65, y: 68 },
        details: "Low bridge over the Musi river prone to flooding within 60 minutes of cloudburst.",
        infrastructureAtRisk: "Causeway bridges, old city drainage outfalls",
      },
    ],
  },
];

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: "scenario-normal",
    name: "Normal Conditions",
    description: "Standard seasonal weather with nominal parameters within safe civic thresholds",
    recommendedLocationId: "palakollu",
    expectedResult: "Low Risk (0–24)",
    envData: {
      temperatureC: 29.0,
      rainfall24hMm: 5.0,
      rainfallIntensityMmH: 1.0,
      humidityPercent: 55,
      condition: "Clear & Mild",
      isSimulated: true,
    },
  },
  {
    id: "scenario-heat",
    name: "Extreme Heat",
    description: "Severe summer heatwave with thermal mass accumulation and prolonged dry heat",
    recommendedLocationId: "hyderabad",
    expectedResult: "High/Critical Heat Risk (75–100)",
    envData: {
      temperatureC: 43.0,
      rainfall24hMm: 0.0,
      rainfallIntensityMmH: 0.0,
      humidityPercent: 35,
      condition: "Extreme Heatwave / Intense Sun",
      isSimulated: true,
    },
  },
  {
    id: "scenario-flood",
    name: "Heavy Rain / Flood",
    description: "Cloudburst monsoon downpour exceeding municipal drainage discharge capacity",
    recommendedLocationId: "palakollu",
    expectedResult: "Critical Flood Risk (82/100)",
    envData: {
      temperatureC: 28.0,
      rainfall24hMm: 145.0,
      rainfallIntensityMmH: 42.0,
      humidityPercent: 91,
      condition: "Torrential Downpour / Monsoon Storm",
      isSimulated: true,
    },
  },
];
