import {
  CityDistrict,
  ClimateAlert,
  ClimateIncident,
  CriticalAsset,
  HistoricalIncident,
  InAppNotification,
  PreparednessPlan,
  RiskMemoryPattern,
  SmartRiskThresholds,
  OperationalRole,
  AlertLifecycleStatus,
  IncidentLifecycleStatus,
  TaskStatus,
  EscalationLevel,
} from "../types/climate";
import { CURATED_INDIAN_LOCATIONS } from "./locationService";

// Standard Smart Risk Thresholds (Section 5)
export const DEFAULT_SMART_THRESHOLDS: SmartRiskThresholds = {
  temperatureCriticalC: 42.0,
  rainfallCritical24hMm: 100.0,
  rainfallIntensityCriticalMmH: 35.0,
  criticalScoreThreshold: 75,
  highScoreThreshold: 60,
};

// Standard Preparedness Plans (Section 11)
export const PREPAREDNESS_PLANS: PreparednessPlan[] = [
  {
    id: "plan-flood",
    name: "Standard Municipal Flood Preparedness & Response Protocol",
    hazard: "Flood Risk",
    description:
      "Operational playbook for heavy cloudbursts, low-lying storm drain inundation, and delta riverback water surges.",
    leadAgencies: [
      "Municipal Corporation Disaster Cell",
      "Public Health Engineering Dept (PHED)",
      "Traffic Police & Arterial Transit Authority",
      "Civil Defence & Home Guards",
    ],
    standardActions: [
      "Inspect municipal arterial drainage networks, culverts, and sluice outfalls",
      "Monitor identified waterlogging-prone sumps, subways, and rail crossings",
      "Deploy dewatering heavy diesel pump units with stand-by operating crews",
      "Pre-position quick response personnel, lifeboats, and barricades at vulnerable zones",
      "Issue real-time public precautionary warnings via regional emergency channels",
      "Establish dry-relief staging shelters with drinking water and medical supplies",
    ],
    targetZonesExample: "Lowland residential basins, delta canal sumps, underpasses",
    beforeEvent: {
      monitoringActions: [
        "Inspect and clear trash grates at main river canal sluice outfalls",
        "Monitor hydrostatic pressure sensors in underground subways and sumps",
        "Verify operational readiness of municipal mobile diesel dewatering pumps",
      ],
      readinessChecks: [
        "Sandbag stockpiles verified at secondary depot (min. 5,000 units)",
        "Emergency fuel reserves topped up for municipal generator sets",
        "Relief shelter power backups and potable water tanks inspected",
      ],
      responsibleTeam: "Engineering Drainage & Early Warning Cell",
    },
    duringEvent: {
      responseActions: [
        "Deploy high-capacity dewatering pump crews to lowest depression nodes",
        "Close inundated subway passages and erect emergency traffic diversions",
        "Activate breach-containment sandbag reinforcement teams along embankments",
      ],
      communicationActions: [
        "Broadcast hourly emergency alert bulletins on municipal SMS & radio channels",
        "Direct emergency vehicular convoys through validated high-elevation bypasses",
        "Liaise with State Disaster Management Authority (SDMA) for mutual aid escalation",
      ],
      safetyActions: [
        "Evacuate vulnerable informal ground-level settlements to dry staging shelters",
        "Disconnect vulnerable low-grade electrical junction boxes in flooded wards",
        "Station quick-response paramedic lifeboats at critical medical choke points",
      ],
    },
    afterEvent: {
      damageAssessment: [
        "Conduct structural integrity survey of flooded road surfaces and culvert foundations",
        "Inspect electrical substations and transformer platforms for moisture damage",
        "Audit contaminated drinking water supply pipelines and borewell wells",
      ],
      recoveryActions: [
        "Clear mud sediment, silt, and tree debris from primary arterial carriage-ways",
        "Carry out anti-larval fogging and chlorine bleaching across inundated residential blocks",
        "Restore full grid electrical power and inspect public hospital substations",
      ],
      closureChecks: [
        "Verify all floodwaters subsided below safe roadbed reference datum",
        "Submit debrief incident reports and log lessons into Risk Memory Engine",
        "De-escalate incident from RECOVERY to RESOLVED",
      ],
    },
  },
  {
    id: "plan-heat",
    name: "Urban Heatwave Preparedness & Public Health Action Plan",
    hazard: "Heat Risk",
    description:
      "Targeted municipal protocol mitigating prolonged solar exposure, urban heat island hardscape retention, and thermal distress.",
    leadAgencies: [
      "Municipal Health Administration",
      "Labour & Employment Inspectorate",
      "Water Supply & Sewerage Board (BWSSB / HMWSSB)",
      "State Disaster Management Authority (SDMA)",
    ],
    standardActions: [
      "Monitor high-exposure urban concrete hardscapes, informal settlements, and outdoor work zones",
      "Issue multi-lingual heat-safety public health warnings and advisory bulletins",
      "Activate municipal emergency drinking-water distribution kiosks (Pyaoos) across transit nodes",
      "Regulate outdoor manual labor during peak solar radiation hours (11:30 AM – 3:30 PM)",
      "Equip primary urban healthcare centers (UHCs) with dedicated IV-hydration and cooling beds",
      "Operate misting cannons and shaded rest zones at major public bus and rail terminals",
    ],
    targetZonesExample: "Dense masonry markets, bus terminals, industrial outdoor yards",
    beforeEvent: {
      monitoringActions: [
        "Monitor wet-bulb globe temperature (WBGT) and satellite land surface temperature anomalies",
        "Track regional weather radar heat advisory bulletins and synoptic pressure ridges",
        "Inspect thermal imaging scans of high-density concrete commercial concourses",
      ],
      readinessChecks: [
        "Verify oral rehydration salts (ORS) and IV fluid stocks at all primary health centers",
        "Inspect continuous chlorination and pressure at municipal drinking water kiosks",
        "Ensure commercial building HVAC backups and hospital cooling systems are operational",
      ],
      responsibleTeam: "Urban Health Surveillance Cell & Meterological Liaison",
    },
    duringEvent: {
      responseActions: [
        "Operate water misting tankers along heavily pedestrianized commercial market streets",
        "Enforce mandatory midday work suspension (11:30 AM – 3:30 PM) for open construction sites",
        "Distribute cooled drinking water and electrolytic packets at interstate transit hubs",
      ],
      communicationActions: [
        "Issue red heatwave advisories via digital traffic message boards and mobile push",
        "Broadcast heatstroke symptom recognition guides in vernacular languages",
        "Coordinate with transport operators to permit emergency hydration breaks for drivers",
      ],
      safetyActions: [
        "Triage acute thermal exhaustion patients in air-conditioned cooling wards",
        "Open public civic halls, libraries, and shaded concourses as cooling shelters",
        "Establish mobile paramedic patrol squads across dense informal settlements",
      ],
    },
    afterEvent: {
      damageAssessment: [
        "Compile total heat-distress and occupational casualty casualty records across city clinics",
        "Assess thermal stress impacts on municipal water distribution network and power transformers",
        "Evaluate compliance rate of outdoor construction work suspension orders",
      ],
      recoveryActions: [
        "Replenish emergency IV fluids and pharmaceuticals at all urban health clinics",
        "Conduct post-heatwave public hygiene and water purity testing at public kiosks",
        "Demobilize temporary shaded tents while maintaining permanent drinking fountains",
      ],
      closureChecks: [
        "Confirm ambient surface temperatures returned below threshold for 48 consecutive hours",
        "Record operational expenditure and intervention efficacy into institutional database",
        "Formally close heatwave emergency ticket and archive into Risk Memory",
      ],
    },
  },
];

export const INITIAL_PREPAREDNESS_PLANS = PREPAREDNESS_PLANS;

// Initial Monitored Locations with Critical Asset Profiles (Section 1, 2, 3)
export const INITIAL_MONITORED_LOCATIONS: CityDistrict[] = [
  {
    ...CURATED_INDIAN_LOCATIONS[0], // Palakollu
    isMonitored: true,
    isImportant: true,
    vulnerabilityLevel: "Critical",
    currentRiskScore: 82,
    currentRiskLevel: "CRITICAL",
    currentHazard: "Flood Risk",
    lastUpdated: "5 mins ago",
    operationalStatus: "Incident Active",
    repeatedIncidentsCount: 6,
    criticalAssets: [
      {
        id: "ast-pal-1",
        name: "Palakollu Government Area Hospital",
        type: "Hospital",
        address: "Near Old Bus Stand, Palakollu",
        vulnerabilityFactor: "Located in delta alluvial hollow; ground floor emergency bay susceptible to storm runoff.",
        coordinates: { lat: 16.5295, lng: 81.728 },
        status: "Heightened Alert",
      },
      {
        id: "ast-pal-2",
        name: "West Godavari Substation & Pump House",
        type: "Utility Facility",
        address: "Canal Bund Road",
        vulnerabilityFactor: "Electrical transformer yard situated near canal overflow lip.",
        coordinates: { lat: 16.532, lng: 81.731 },
        status: "Heightened Alert",
      },
      {
        id: "ast-pal-3",
        name: "Municipal Bus Depot & RTC Concourse",
        type: "Public Infrastructure",
        address: "Main Highway Intersection",
        vulnerabilityFactor: "Key evacuation transit lifeline; low road grade prone to 0.4m standing water.",
        coordinates: { lat: 16.526, lng: 81.725 },
        status: "Impacted",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[1], // Narsapuram
    isMonitored: true,
    isImportant: true,
    vulnerabilityLevel: "High",
    currentRiskScore: 68,
    currentRiskLevel: "HIGH",
    currentHazard: "Flood Risk",
    lastUpdated: "12 mins ago",
    operationalStatus: "Alert Active",
    repeatedIncidentsCount: 4,
    criticalAssets: [
      {
        id: "ast-nar-1",
        name: "Narsapuram Port Ferry Terminal & Jetty",
        type: "Public Infrastructure",
        address: "Vasista Godavari Estuary bank",
        vulnerabilityFactor: "High tidal backflow directly affects embarkation ramp during coastal squalls.",
        coordinates: { lat: 16.438, lng: 81.698 },
        status: "Heightened Alert",
      },
      {
        id: "ast-nar-2",
        name: "Coastal Fisheries Processing Yard",
        type: "Industrial Facility",
        address: "Biyyaputippa Road",
        vulnerabilityFactor: "Sensitive refrigerated cold storage near saline creek bank.",
        coordinates: { lat: 16.425, lng: 81.705 },
        status: "Normal",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[2], // Vijayawada
    isMonitored: true,
    isImportant: false,
    vulnerabilityLevel: "Medium",
    currentRiskScore: 48,
    currentRiskLevel: "MEDIUM",
    currentHazard: "Heat Risk",
    lastUpdated: "18 mins ago",
    operationalStatus: "Monitoring",
    repeatedIncidentsCount: 3,
    criticalAssets: [
      {
        id: "ast-vij-1",
        name: "New Government General Hospital (GGH)",
        type: "Hospital",
        address: "Gunadala, Vijayawada",
        vulnerabilityFactor: "High patient volume; requires uninterrupted backup power during peak thermal heat spikes.",
        coordinates: { lat: 16.518, lng: 80.648 },
        status: "Normal",
      },
      {
        id: "ast-vij-2",
        name: "Pandit Nehru Bus Station (PNBS)",
        type: "Public Infrastructure",
        address: "Krishna River Bund",
        vulnerabilityFactor: "Massive metal-roofed concourse generating severe microclimate heat traps.",
        coordinates: { lat: 16.507, lng: 80.618 },
        status: "Normal",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[3], // Visakhapatnam
    isMonitored: true,
    isImportant: true,
    vulnerabilityLevel: "High",
    currentRiskScore: 74,
    currentRiskLevel: "HIGH",
    currentHazard: "Flood Risk",
    lastUpdated: "8 mins ago",
    operationalStatus: "Alert Active",
    repeatedIncidentsCount: 5,
    criticalAssets: [
      {
        id: "ast-viz-1",
        name: "King George Hospital (KGH)",
        type: "Hospital",
        address: "Maharanipeta, Visakhapatnam",
        vulnerabilityFactor: "Coastal drainage capacity bottleneck during cyclonic squalls.",
        coordinates: { lat: 17.705, lng: 83.308 },
        status: "Heightened Alert",
      },
      {
        id: "ast-viz-2",
        name: "Visakhapatnam Steel Industrial Complex",
        type: "Industrial Facility",
        address: "Gajuwaka Industrial Zone",
        vulnerabilityFactor: "Heavy surface imperviousness generating large stormwater surge into local canals.",
        coordinates: { lat: 17.652, lng: 83.185 },
        status: "Normal",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[4], // Hyderabad
    isMonitored: true,
    isImportant: false,
    vulnerabilityLevel: "Critical",
    currentRiskScore: 86,
    currentRiskLevel: "CRITICAL",
    currentHazard: "Heat Risk",
    lastUpdated: "3 mins ago",
    operationalStatus: "Alert Active",
    repeatedIncidentsCount: 5,
    criticalAssets: [
      {
        id: "ast-hyd-1",
        name: "Osmania General Hospital",
        type: "Hospital",
        address: "Afzal Gunj, Hyderabad",
        vulnerabilityFactor: "Heritage masonry in dense commercial core with prolonged nocturnal heat retention.",
        coordinates: { lat: 17.378, lng: 78.476 },
        status: "Heightened Alert",
      },
      {
        id: "ast-hyd-2",
        name: "HITEC City Substation 220kV",
        type: "Utility Facility",
        address: "Madhapur",
        vulnerabilityFactor: "Grid peak load strain during ambient 43°C conditions.",
        coordinates: { lat: 17.447, lng: 78.378 },
        status: "Normal",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[5], // Araku Valley
    isMonitored: true,
    isImportant: false,
    vulnerabilityLevel: "Medium",
    currentRiskScore: 32,
    currentRiskLevel: "LOW",
    currentHazard: "Flood Risk",
    lastUpdated: "25 mins ago",
    operationalStatus: "Monitoring",
    repeatedIncidentsCount: 2,
    criticalAssets: [
      {
        id: "ast-ara-1",
        name: "Community Health Centre Araku",
        type: "Hospital",
        address: "Main Ghat Road",
        vulnerabilityFactor: "Sole medical facility for regional tribal hamlets; road access vulnerable to landslides.",
        coordinates: { lat: 18.332, lng: 82.882 },
        status: "Normal",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[6], // Mumbai
    isMonitored: true,
    isImportant: true,
    vulnerabilityLevel: "High",
    currentRiskScore: 71,
    currentRiskLevel: "HIGH",
    currentHazard: "Flood Risk",
    lastUpdated: "10 mins ago",
    operationalStatus: "Monitoring",
    repeatedIncidentsCount: 7,
    criticalAssets: [
      {
        id: "ast-mum-1",
        name: "KEM Hospital & Medical College",
        type: "Hospital",
        address: "Parel, Mumbai",
        vulnerabilityFactor: "Central depression catchment prone to sewer backflow during high tide rainfall.",
        coordinates: { lat: 19.002, lng: 72.842 },
        status: "Normal",
      },
    ],
  },
  {
    ...CURATED_INDIAN_LOCATIONS[7], // Delhi
    isMonitored: true,
    isImportant: true,
    vulnerabilityLevel: "High",
    currentRiskScore: 65,
    currentRiskLevel: "HIGH",
    currentHazard: "Heat Risk",
    lastUpdated: "14 mins ago",
    operationalStatus: "Monitoring",
    repeatedIncidentsCount: 6,
    criticalAssets: [
      {
        id: "ast-del-1",
        name: "AIIMS New Delhi Central Trauma Facility",
        type: "Hospital",
        address: "Ansari Nagar East, New Delhi",
        vulnerabilityFactor: "Massive acute casualty intake during regional heat stroke emergencies.",
        coordinates: { lat: 28.567, lng: 77.21 },
        status: "Normal",
      },
    ],
  },
];

// Initial Alerts with complete Phase 2 Lifecycle (Section 6)
export const INITIAL_ALERTS: ClimateAlert[] = [
  {
    id: "ALT-2026-104",
    locationId: "palakollu",
    locationName: "Palakollu",
    state: "Andhra Pradesh",
    isActive: true,
    level: "CRITICAL",
    hazard: "Flood Risk",
    title: "CRITICAL FLOOD RISK DETECTED",
    score: 82,
    message:
      "Precipitation of 145mm combined with 42mm/hr downpour intensity exceeds local 22mm/hr delta drainage capacity.",
    actionGuidance:
      "Execute Immediate Flood Response Protocol; mobilize pump squads and issue alert to West Godavari Canal Zone.",
    issuedAt: "10:14 AM Today",
    code: "CS-ALERT-FLD-82",
    status: "IN PROGRESS",
    acknowledgedBy: "R. Sharma (Response Operator)",
    acknowledgedAt: "10:17 AM Today",
    incidentId: "CS-1042",
    thresholdExceeded: "Rainfall (145mm > 100mm threshold) & Intensity (42mm/hr > 35mm/hr)",
  },
  {
    id: "ALT-2026-103",
    locationId: "hyderabad",
    locationName: "Hyderabad",
    state: "Telangana",
    isActive: true,
    level: "CRITICAL",
    hazard: "Heat Risk",
    title: "CRITICAL HEAT RISK DETECTED",
    score: 86,
    message:
      "Severe heatwave conditions reaching 43.0°C with 86% impervious concrete cover producing high diurnal heat storage.",
    actionGuidance:
      "Deploy public hydration stations at transit hubs and restrict afternoon outdoor construction.",
    issuedAt: "09:40 AM Today",
    code: "CS-ALERT-HEAT-86",
    status: "ACKNOWLEDGED",
    acknowledgedBy: "K. Reddy (Risk Analyst)",
    acknowledgedAt: "09:45 AM Today",
    thresholdExceeded: "Temperature (43.0°C > 42.0°C critical threshold)",
  },
  {
    id: "ALT-2026-102",
    locationId: "visakhapatnam",
    locationName: "Visakhapatnam",
    state: "Andhra Pradesh",
    isActive: true,
    level: "HIGH",
    hazard: "Flood Risk",
    title: "HIGH FLOOD & TIDAL SURGE RISK",
    score: 74,
    message:
      "Coastal rainfall intensity of 34mm/hr with 92mm accumulation approaching low-lying port subway choke points.",
    actionGuidance:
      "Clear stormwater grates along Beach Road and station emergency rescue teams at Convent Junction.",
    issuedAt: "08:55 AM Today",
    code: "CS-ALERT-FLD-74",
    status: "NEW",
    thresholdExceeded: "Score (74 > 60 High Risk Threshold)",
  },
  {
    id: "ALT-2026-101",
    locationId: "narsapuram",
    locationName: "Narsapuram",
    state: "Andhra Pradesh",
    isActive: true,
    level: "HIGH",
    hazard: "Flood Risk",
    title: "ELEVATED ESTUARY INUNDATION RISK",
    score: 68,
    message:
      "High tide backflow coinciding with 78mm 24h rainfall in Godavari river mouth lowlands.",
    actionGuidance:
      "Precautionary sandbag reinforcement at Biyyaputippa embankment; alert fish landing jetties.",
    issuedAt: "07:30 AM Today",
    code: "CS-ALERT-FLD-68",
    status: "ASSIGNED",
    acknowledgedBy: "V. Naidu (Operator)",
    acknowledgedAt: "07:42 AM Today",
  },
  {
    id: "ALT-2026-098",
    locationId: "vijayawada",
    locationName: "Vijayawada",
    state: "Andhra Pradesh",
    isActive: false,
    level: "MEDIUM",
    hazard: "Heat Risk",
    title: "MODERATE HEAT ALERT",
    score: 48,
    message: "Mid-day temperatures reached 38.5°C; elevated heat index in commercial transit markets.",
    actionGuidance: "Standard public hydration advisories issued across PNBS bus concourse.",
    issuedAt: "Yesterday 02:00 PM",
    code: "CS-ALERT-HEAT-48",
    status: "RESOLVED",
    acknowledgedBy: "P. Varma (Manager)",
    acknowledgedAt: "Yesterday 02:15 PM",
  },
];

// Initial Operational Incidents with complete Task Assignment & Recovery (Section 7, 9, 11, 12)
export const INITIAL_INCIDENTS: ClimateIncident[] = [
  {
    id: "CS-1042",
    locationId: "palakollu",
    locationName: "Palakollu",
    state: "Andhra Pradesh",
    hazard: "Flood Risk",
    severity: "CRITICAL",
    riskScore: 82,
    status: "RESPONSE",
    title: "Canal Outfall & Depressed Sump Inundation",
    summary:
      "Intense 42mm/hr cloudburst causing Godavari delta branch canals to back up through municipal stormwater culverts near Main RTC Depot.",
    createdAt: "Today 10:15 AM",
    acknowledgedAt: "Today 10:18 AM",
    responseStartedAt: "Today 10:25 AM",
    ownerName: "R. Sharma",
    ownerRole: "Response Operator",
    escalationLevel: "Level 2 - Municipal Manager",
    escalationReason: "Local stormwater conduits running at 140% hydraulic capacity; backup pumps required.",
    attachedPlanId: "plan-flood",
    tasks: [
      {
        id: "tsk-1042-1",
        incidentId: "CS-1042",
        title: "Inspect and clear primary drainage outfalls at Railway Culvert",
        assignedTo: "Drainage Rapid Squad Alpha (PHED)",
        department: "Engineering & Drainage",
        priority: "Critical",
        dueTime: "Within 45 mins",
        status: "IN PROGRESS",
        notes: "Debris gate cleared; 2 sluice gates manually cranked open to relieve backpressure.",
      },
      {
        id: "tsk-1042-2",
        incidentId: "CS-1042",
        title: "Deploy 2x 150HP dewatering pump sets at RTC Bus Stand depression",
        assignedTo: "Emergency Pumping Division",
        department: "Disaster Operations",
        priority: "Critical",
        dueTime: "Within 60 mins",
        status: "COMPLETED",
        notes: "Both pumps operational, discharging 1,800 LPM into secondary relief canal.",
      },
      {
        id: "tsk-1042-3",
        incidentId: "CS-1042",
        title: "Erect safety barricades at waterlogged Market Underpass",
        assignedTo: "Traffic & Municipal Marshals",
        department: "Traffic Police",
        priority: "High",
        dueTime: "Within 30 mins",
        status: "COMPLETED",
        notes: "Vehicular traffic safely diverted toward bypass road.",
      },
      {
        id: "tsk-1042-4",
        incidentId: "CS-1042",
        title: "Broadcast precautionary public safety warning to local wards",
        assignedTo: "Civil Defence Public Relations",
        department: "Public Information",
        priority: "High",
        dueTime: "Immediate",
        status: "COMPLETED",
        notes: "SMS alerts and loudspeaker vans deployed across Wards 4 through 12.",
      },
    ],
    timeline: [
      {
        id: "tl-1",
        timestamp: "10:15 AM",
        stage: "DETECTED",
        title: "Critical Flood Risk Detected by Telemetry Engine",
        actor: "ClimateShield Telemetry Node",
        details: "Rainfall exceeded 145mm threshold with 42mm/hr sustained intensity.",
      },
      {
        id: "tl-2",
        timestamp: "10:18 AM",
        stage: "ACKNOWLEDGED",
        title: "Alert Acknowledged & Incident Formalized",
        actor: "R. Sharma (Response Operator)",
        details: "Severity confirmed as CRITICAL; Incident #CS-1042 created.",
      },
      {
        id: "tl-3",
        timestamp: "10:25 AM",
        stage: "RESPONSE",
        title: "Emergency Response Directives Dispatched",
        actor: "Response Operations Center",
        details: "Standard Flood Preparedness Plan activated; 4 operational tasks assigned.",
      },
      {
        id: "tl-4",
        timestamp: "10:45 AM",
        stage: "RESPONSE",
        title: "Incident Escalated to Municipal Manager",
        actor: "R. Sharma (Response Operator)",
        details: "Escalated to Level 2 for inter-departmental pump reallocation.",
      },
    ],
  },
  {
    id: "CS-1039",
    locationId: "hyderabad",
    locationName: "Hyderabad",
    state: "Telangana",
    hazard: "Heat Risk",
    severity: "CRITICAL",
    riskScore: 86,
    status: "ACKNOWLEDGED",
    title: "Urban Heat Island Core Heatwave Crisis",
    summary:
      "Prolonged 43°C heatwave across Old City and Secunderabad transit corridors with acute risk to informal outdoor workers.",
    createdAt: "Today 09:42 AM",
    acknowledgedAt: "Today 09:48 AM",
    ownerName: "K. Reddy",
    ownerRole: "Risk Analyst",
    escalationLevel: "Level 1 - Response Operator",
    attachedPlanId: "plan-heat",
    tasks: [
      {
        id: "tsk-1039-1",
        incidentId: "CS-1039",
        title: "Open 18 emergency hydration kiosks along Charminar market streets",
        assignedTo: "GHMC Health Division",
        department: "Public Health",
        priority: "High",
        dueTime: "11:30 AM",
        status: "IN PROGRESS",
        notes: "12 kiosks stocked with chilled electrolyte packets and drinking water.",
      },
      {
        id: "tsk-1039-2",
        incidentId: "CS-1039",
        title: "Issue mandatory work suspension order for midday construction sites",
        assignedTo: "Labour Department Enforcement",
        department: "Labour Inspectorate",
        priority: "High",
        dueTime: "11:00 AM",
        status: "COMPLETED",
        notes: "Inspection teams dispatched across Cyberabad and Financial District.",
      },
    ],
    timeline: [
      {
        id: "tl-hyd-1",
        timestamp: "09:42 AM",
        stage: "DETECTED",
        title: "Heat Risk Score 86 Triggered Alert",
        actor: "ClimateShield Engine",
        details: "Calculated heat severity passed 75 critical threshold.",
      },
      {
        id: "tl-hyd-2",
        timestamp: "09:48 AM",
        stage: "ACKNOWLEDGED",
        title: "Incident Logged by Risk Analyst",
        actor: "K. Reddy (Risk Analyst)",
        details: "Operational brief routed to municipal health inspectorate.",
      },
    ],
  },
  {
    id: "CS-1028",
    locationId: "visakhapatnam",
    locationName: "Visakhapatnam",
    state: "Andhra Pradesh",
    hazard: "Flood Risk",
    severity: "HIGH",
    riskScore: 76,
    status: "RECOVERY",
    title: "Convent Junction Underpass Flooding",
    summary:
      "Tidal high-surge storm runoff inundated Convent Junction port feeder road, disrupting harbor freight.",
    createdAt: "Yesterday 04:30 PM",
    acknowledgedAt: "Yesterday 04:35 PM",
    responseStartedAt: "Yesterday 04:50 PM",
    recoveryStartedAt: "Today 08:00 AM",
    ownerName: "M. Rao",
    ownerRole: "Response Operator",
    escalationLevel: "Level 2 - Municipal Manager",
    attachedPlanId: "plan-flood",
    resolutionNotes: "Stormwater drained; silt removal completed across 1.2km road stretch.",
    tasks: [
      {
        id: "tsk-1028-1",
        incidentId: "CS-1028",
        title: "Dewater and sweep mud sediment from junction roadbed",
        assignedTo: "GVMC Sanitation & Roads",
        department: "Sanitation",
        priority: "High",
        dueTime: "Completed",
        status: "COMPLETED",
        notes: "Road surface cleared and inspected for asphalt potholes.",
      },
    ],
    timeline: [
      {
        id: "tl-viz-1",
        timestamp: "Yesterday 04:30 PM",
        stage: "DETECTED",
        title: "Severe Waterlogging Detected",
        actor: "Sensor Network",
        details: "Water level rose to 0.55m on road surface.",
      },
      {
        id: "tl-viz-2",
        timestamp: "Today 08:00 AM",
        stage: "RECOVERY",
        title: "Transitioned to Recovery Stage",
        actor: "M. Rao (Operator)",
        details: "All floodwater cleared; recovery and silt washing in progress.",
      },
    ],
  },
  {
    id: "CS-1015",
    locationId: "mumbai",
    locationName: "Mumbai",
    state: "Maharashtra",
    hazard: "Flood Risk",
    severity: "HIGH",
    riskScore: 78,
    status: "RESOLVED",
    title: "Milan Subway Monsoon Sump Flooding",
    summary: "High-intensity rainfall submerged subway roadbed under 0.8m water during high tide.",
    createdAt: "Sep 07, 2026 01:15 PM",
    acknowledgedAt: "Sep 07, 2026 01:20 PM",
    responseStartedAt: "Sep 07, 2026 01:30 PM",
    recoveryStartedAt: "Sep 07, 2026 04:00 PM",
    resolvedAt: "Sep 07, 2026 06:15 PM",
    ownerName: "S. Kulkarni",
    ownerRole: "Manager",
    escalationLevel: "Level 2 - Municipal Manager",
    attachedPlanId: "plan-flood",
    resolutionNotes:
      "Dual stormwater pumps cleared 100% of standing water in 2.5 hours. Traffic restored normally.",
    tasks: [],
    timeline: [
      {
        id: "tl-mum-1",
        timestamp: "Sep 07 01:15 PM",
        stage: "DETECTED",
        title: "Subway Sensor Water Level Alert",
        actor: "BMC Sensor Grid",
        details: "Subway closed to light vehicular traffic.",
      },
      {
        id: "tl-mum-2",
        timestamp: "Sep 07 06:15 PM",
        stage: "RESOLVED",
        title: "Incident Formally Resolved",
        actor: "S. Kulkarni (Manager)",
        details: "Subway reopened; post-incident engineering debrief completed.",
      },
    ],
  },
];

// Historical Incident Intelligence Records (Section 4)
export const INITIAL_HISTORICAL_INCIDENTS: HistoricalIncident[] = [
  {
    id: "hist-01",
    incidentCode: "CS-1015",
    locationId: "mumbai",
    locationName: "Mumbai",
    state: "Maharashtra",
    hazard: "Flood Risk",
    dateTime: "Sep 07, 2026 13:15",
    riskScore: 78,
    severity: "HIGH",
    responseStatus: "Resolved",
    resolutionTimeHours: 5.0,
    zoneAffected: "Milan Subway & Hindmata Junction",
    actionsTaken: [
      "Subway traffic closure & warning beacons",
      "Activation of high-capacity storm pumps",
      "Debris gate clearance at sluice outfall",
    ],
    keyLessonLearned:
      "Automated sensor-triggered barriers prevent vehicles from driving into deceptive standing water.",
  },
  {
    id: "hist-02",
    incidentCode: "CS-0982",
    locationId: "palakollu",
    locationName: "Palakollu",
    state: "Andhra Pradesh",
    hazard: "Flood Risk",
    dateTime: "Aug 24, 2026 06:30",
    riskScore: 84,
    severity: "CRITICAL",
    responseStatus: "Resolved",
    resolutionTimeHours: 8.5,
    zoneAffected: "Canal Bund Sump & Vegetable Market",
    actionsTaken: [
      "Breach reinforcement with 4,000 sandbags",
      "Evacuation of 120 low-lying informal homes",
      "Deployment of 3 portable generator pump trailers",
    ],
    keyLessonLearned:
      "Canal gate maintenance must be synchronized with upstream dam release schedules to prevent backflow.",
  },
  {
    id: "hist-03",
    incidentCode: "CS-0955",
    locationId: "hyderabad",
    locationName: "Hyderabad",
    state: "Telangana",
    hazard: "Heat Risk",
    dateTime: "Aug 12, 2026 11:00",
    riskScore: 88,
    severity: "CRITICAL",
    responseStatus: "Resolved",
    resolutionTimeHours: 6.0,
    zoneAffected: "Old City Commercial Concourses",
    actionsTaken: [
      "Establishment of 24 temporary hydration stations",
      "Water misting cannon runs along arterial corridors",
      "Emergency triage for 38 heat-exhaustion cases",
    ],
    keyLessonLearned:
      "Reflective tarpaulin shading across open pedestrian retail streets reduced surface radiant temperature by 5.2°C.",
  },
  {
    id: "hist-04",
    incidentCode: "CS-0910",
    locationId: "visakhapatnam",
    locationName: "Visakhapatnam",
    state: "Andhra Pradesh",
    hazard: "Flood Risk",
    dateTime: "Jul 18, 2026 15:45",
    riskScore: 72,
    severity: "HIGH",
    responseStatus: "Resolved",
    resolutionTimeHours: 4.5,
    zoneAffected: "Beach Road Low Outfalls",
    actionsTaken: [
      "Sand buildup dredged from sea drainage mouths",
      "Diverted coastal commuter traffic",
      "Deployed municipal backhoe to unblock culvert",
    ],
    keyLessonLearned:
      "High tide tide-gates require automated hydraulic closing to stop tidal seawater from entering inland storm lines.",
  },
  {
    id: "hist-05",
    incidentCode: "CS-0870",
    locationId: "delhi",
    locationName: "Delhi",
    state: "Delhi",
    hazard: "Heat Risk",
    dateTime: "Jun 22, 2026 12:30",
    riskScore: 85,
    severity: "CRITICAL",
    responseStatus: "Resolved",
    resolutionTimeHours: 7.0,
    zoneAffected: "Connaught Place Outer Ring",
    actionsTaken: [
      "Public advisory on regional FM and metro displays",
      "Suspension of manual street sweeping during mid-day",
      "Cool-roof coating inspection on municipal clinics",
    ],
    keyLessonLearned:
      "Transit hubs require continuous cooled drinking water supplies to protect inter-state commuters.",
  },
];

// Unique Phase 2 Feature: Risk Memory / Recurring Risk Patterns (Section 13)
export const INITIAL_RISK_MEMORY_PATTERNS: RiskMemoryPattern[] = [
  {
    id: "rm-1",
    locationId: "palakollu",
    locationName: "Palakollu",
    zoneAffected: "Zone 3 - West Godavari Canal Sump & Lowland Market",
    hazard: "Flood Risk",
    previousIncidentsCount: 6,
    riskPattern: "Recurring",
    lastIncidentDate: "Aug 24, 2026",
    vulnerabilityExplanation:
      "Zone sits 1.8m below the regional irrigation canal embankment grade. Rainfall intensity exceeding 30mm/hr causes gravity drainage reversal.",
    preparednessRecommendation:
      "Pre-position portable diesel pump units before monsoon surges; maintain permanent check-valves on canal outlets.",
    priorityLevel: "Critical",
  },
  {
    id: "rm-2",
    locationId: "hyderabad",
    locationName: "Hyderabad",
    zoneAffected: "Zone 1 - Afzal Gunj & Charminar High-Density Hardscape",
    hazard: "Heat Risk",
    previousIncidentsCount: 5,
    riskPattern: "Recurring",
    lastIncidentDate: "Aug 12, 2026",
    vulnerabilityExplanation:
      "Dense 88% asphalt/masonry urban canyon with zero green canopy cover. Diurnal surface heat retention keeps midnight temperatures above 33°C.",
    preparednessRecommendation:
      "Install permanent misting cool-corridors and enforce cool-roof whitewashing across commercial market roofs.",
    priorityLevel: "Critical",
  },
  {
    id: "rm-3",
    locationId: "mumbai",
    locationName: "Mumbai",
    zoneAffected: "Milan Subway & Hindmata Natural Depression Sump",
    hazard: "Flood Risk",
    previousIncidentsCount: 7,
    riskPattern: "Critical Chronic Hotspot",
    lastIncidentDate: "Sep 07, 2026",
    vulnerabilityExplanation:
      "Historic bowl-shaped topography below high-tide sea level. Retains street runoff whenever tide height > 4.2m.",
    preparednessRecommendation:
      "Operate underground holding tank system (25,000 cu.m capacity) and automate water-sensor traffic barrier gates.",
    priorityLevel: "Critical",
  },
  {
    id: "rm-4",
    locationId: "visakhapatnam",
    locationName: "Visakhapatnam",
    zoneAffected: "Convent Junction Coastal Creek Discharge",
    hazard: "Flood Risk",
    previousIncidentsCount: 4,
    riskPattern: "Seasonal Vulnerability",
    lastIncidentDate: "Jul 18, 2026",
    vulnerabilityExplanation:
      "Creek mouth narrows near harbor road; tidal silt accumulation chokes discharge during cloudbursts.",
    preparednessRecommendation:
      "Pre-monsoon mechanical desilting of creek bed and rapid-deploy sandbag stockpile.",
    priorityLevel: "High",
  },
];

export const INITIAL_RISK_PATTERNS = INITIAL_RISK_MEMORY_PATTERNS;

// Initial In-App Operational Notifications (Section 16)
export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: "notif-1",
    title: "Critical Flood Risk Detected",
    message: "Palakollu score reached 82/100. Rainfall intensity 42mm/hr exceeded safe drainage limits.",
    type: "alert",
    timestamp: "10:14 AM",
    isRead: false,
    linkTab: "alerts",
    relatedId: "ALT-2026-104",
  },
  {
    id: "notif-2",
    title: "New Incident Created: CS-1042",
    message: "Palakollu flood incident formalized. Standard Flood Preparedness Plan attached.",
    type: "incident",
    timestamp: "10:18 AM",
    isRead: false,
    linkTab: "incidents",
    relatedId: "CS-1042",
  },
  {
    id: "notif-3",
    title: "Task Completed",
    message: "Safety barricades erected at Market Underpass in Palakollu.",
    type: "task",
    timestamp: "10:35 AM",
    isRead: true,
    linkTab: "incidents",
    relatedId: "CS-1042",
  },
  {
    id: "notif-4",
    title: "Incident Escalated to Manager",
    message: "Incident #CS-1042 escalated to Level 2 for regional pump reallocation.",
    type: "escalation",
    timestamp: "10:45 AM",
    isRead: false,
    linkTab: "incidents",
    relatedId: "CS-1042",
  },
  {
    id: "notif-5",
    title: "Incident Resolved",
    message: "Milan Subway incident #CS-1015 marked RESOLVED. All standing water cleared.",
    type: "resolved",
    timestamp: "Sep 07 06:15 PM",
    isRead: true,
    linkTab: "reports",
    relatedId: "CS-1015",
  },
];

// Section 12: Recovery Tracking Records (ASSESSMENT -> RESTORATION -> VERIFICATION -> RESOLVED)
export const INITIAL_RECOVERY_RECORDS: import("../types/climate").RecoveryRecord[] = [
  {
    id: "rec-1028-1",
    incidentId: "CS-1028",
    locationId: "visakhapatnam",
    locationName: "Visakhapatnam",
    assetId: "ast-viz-1",
    assetName: "King George Hospital (KGH) Feeder Road",
    assetType: "Road",
    stage: "RESTORATION",
    progressPercent: 75,
    assignedTeam: "Municipal Works & Civil Infrastructure Dept",
    damageAssessmentNotes:
      "0.4m sea-surge waterlogging caused bitumen peeling and heavy mud sedimentation across 400m feeder carriageway.",
    restorationAction:
      "Dewatering completed; cold-mix asphalt patch restoration underway; hydraulic culvert trash racks reconstructed.",
    verificationNotes: "Visual transit test conducted for light vehicles; full heavy bus access pending final road rolling.",
    startedAt: "Today 08:00 AM",
    targetCompletion: "Today 05:00 PM",
    isCompleted: false,
  },
  {
    id: "rec-1042-1",
    incidentId: "CS-1042",
    locationId: "palakollu",
    locationName: "Palakollu",
    assetId: "ast-pal-3",
    assetName: "Municipal Bus Depot & RTC Concourse",
    assetType: "Public Infrastructure" as any,
    stage: "ASSESSMENT",
    progressPercent: 35,
    assignedTeam: "Disaster Operations & Transport Engineering",
    damageAssessmentNotes:
      "Depot concourse submerged under 0.35m runoff; electrical distribution panels isolated as precaution.",
    restorationAction:
      "Deploying high-discharge portable axial pumps; de-silting depot perimeter drainage trench.",
    startedAt: "Today 10:45 AM",
    targetCompletion: "Tomorrow 10:00 AM",
    isCompleted: false,
  },
  {
    id: "rec-1015-1",
    incidentId: "CS-1015",
    locationId: "mumbai",
    locationName: "Mumbai",
    assetId: "ast-mum-1",
    assetName: "Milan Subway Road & Sump Drainage",
    assetType: "Drainage system",
    stage: "RESOLVED",
    progressPercent: 100,
    assignedTeam: "Brihanmumbai Stormwater Maintenance Squad",
    damageAssessmentNotes: "Tidal monsoon downpour inundated subway floor under 0.8m water.",
    restorationAction: "Dual submersible 300HP pump banks evacuated 14,000 cu.m floodwater; surface cleaned with high-pressure jets.",
    verificationNotes: "Safety inspection passed; water clearance sensor calibrated; arterial subway reopened to traffic.",
    startedAt: "Sep 07, 2026 04:00 PM",
    targetCompletion: "Sep 07, 2026 06:15 PM",
    isCompleted: true,
  },
];
